### ISSUE TITLE
Incorrect use of $()

### ISSUE THREAD

**Issue by greenaar** [geektx/Proxmox-VM-Template#1]
The shell script is using $() where it should be using ${}, or in some cases "$"

$() is for command expansion, but it is being used with variables which are *not* commands.

As a result you get things like:

./build-image.sh: 31: template-name: not found

Which is what happens when you try to run a command called 'template-name', instead of referencing it as a variable.

It's worth running this through shellcheck after doing replacements on $() to ${}.

Great concept regardless, and a nice writeup.  Just a few minor bugs.

Cheers!

**Comment by geektx** [comment]
This should be addressed with the current commit.
