### ISSUE TITLE
build-info-file-location should be build_info_file_location

### ISSUE THREAD

**Issue by greenaar** [geektx/Proxmox-VM-Template#2]
Per the title, the variable in build-vars isn't correctly referenced in the build-image script due to a name mismatch.

**Comment by greenaar** [comment]
Same is true with cloud-init-user.

**Comment by geektx** [comment]
thanks for pointing this out. I corrected my local repo and what I put in
the blog but failed to update my online repo. I'll get that taken care of.
Rodney
